import { Module, Global } from '@nestjs/common'; // HEMOS CREADO UN MODULO GLOBAL, ES DECIR QUE PODREMOS HACER USO DE LOS PROVIDERS O CONTROLADORES QUE CONTENGA ESTE MODULO SIN NEECESIDAD DE IMPORTARLO.

const API_KEY = '123456'; // ADEMAS DE INYECTAR CLASES O SERVICIOS EN CONTROLADORES PODEMOS INYECTAR VALORES UNICOS.
const API_KEY_PROD = 'PROD12312';

@Global() // EL DECORADOR GLOBAL LE INDICA A NEST QUE ESTE SERA UN MODULO GLOBAL.
@Module({
  providers: [
    {
      provide: 'API_KEY',
      useValue: process.env.NODE_ENV === 'prod' ? API_KEY_PROD : API_KEY, // ESTA ES LA FORMA DE ENVIAR ESOS VALORES PARA INYECTAR
    },
  ],
  exports: ['API_KEY']
})
export class DatabaseModule {}

// PUEDE SER USADO PARA VARIABLES QUE NO CAMBIAN SU VALOR COMO UNA API KEY, CONEXION A BASE DE DATOS ETC. TAMBIEN SE PODRIA UTILIZAR PARA SERVICIOS ESTANDARES COMO UN CRUD.
// YA QUE POR LO GENERAL CASI TODOS LOS MODULOS REQUIEREN DE UN CRUD PERO SOLO EN CASO DE QUE LA APLICACION LO REQUIERA. NO ES LO MAS RECOMENDABLE.
